- plugins/pltbrowser/pltbrowser.c
Allows the user to move tracks between playlists, just like with ddb_tabstrip.
> pltbrowser: switch playlist on drag-motion event

- plugins/pltbrowser/pltbrowser.c
> pltbrowser: add playing column and don't activate playlist on right

- plugins/gtkui/plcommon.c
- plugins/pltbrowser/pltbrowser.c
Diff looks pretty complex, but this patch just added an if check and missing plt_unref:
```
if (plt) {
...
deadbeef->plt_unref (plt);
}
```
> pltbrowser: fix memleak

- plugins/gtkui/ddblistview.c
To fix issue #1294.  Also redraws the headers on the same pixel that a column is moved.
> gtkui: new column dragging algorithm

- plugins/gtkui/ddblistview.c
- plugins/gtkui/ddblistview.h
> Fix some issues with dragdrop position and selection

- plugins/gtkui/ddblistview.c
> gtkui: fix wrong track being dropped with drag and drop

- plugins/gtkui/ddblistview.c
(Hopefully) last bit to fix #1319
> gtkui: fix wrong drop pos when hovering album art

- plugins/gtkui/ddblistview.c
fixes an issue mentioned in #1341
> gtkui: completely disable drag and drop support in searchlist

- plugins/gtkui/widgets.c
Screenshot: ![](http://i.imgur.com/UH4xLRZ.png)
> gtkui: add widget title at the top of the design mode context menu item and use widget title for new tabs in the tab widget

- plugins/gtkui/ddblistview.c
This reverts a playlist sort order to the default "unsorted" state when the column it is currently sorted by is removed.  This is only really meaningful for the search playlist at the moment.  The unsorted state for the main playlist is just to stay however it is.
> gtkui: unsort playlist when a sorted column is removed

- plugins/gtkui/widgets.c
> gtkui: make sure to redraw coverart widget when playback stops

- plugins/gtkui/ddblistview.c
- plugins/gtkui/ddblistview.h
- plugins/gtkui/plcommon.c
> gtkui: auto-resize columns

- plugins/gtkui/ddblistview.c
- plugins/gtkui/plcommon.c
> gtkui: fix jerky scrolling when resizing at the end of the listview

- plugins/converter/converter.glade
- plugins/converter/convgui.c
- plugins/converter/interface.c
> converter: add preview of output files to gtk ui

- plugins/gtkui/plcommon.c
> Fix missing conf_unlock() in import_column_config_0_6()

- main.c
- plugins/cocoaui/AppDelegate.m
- plugins/cocoaui/Converter.xib
- plugins/cocoaui/ConverterWindowController.h
- plugins/cocoaui/ConverterWindowController.m
Deadbeef is now associated with the filetypes it can decode (for the current osx build) in finder. That is user can open a file with Deadbeef from finder;
In the converter panel of deadbeef the filename preview field is filled.
> Work on cocoaui: File association in finder and converter panel filename preview

- tf.c
I hope everything is alright. I am no professional c developer.
> tf: Implement $num(n,len) (fixes #1279)

- plugins/gtkui/gtkui.c
partial fix for issues #618 and #521
> add option to start in tray: tray.start_minimized

- plugins/gtkui/gtkui.c
- plugins/gtkui/gtkui.h
- plugins/gtkui/pltmenu.c
Hello again,
I wanted to have a go at working on https://github.com/Alexey-Yakovenko/deadbeef/issues/1630
I have it working on linux, but can't test it on OSX (and noticed it likely needs to be added to https://github.com/Alexey-Yakovenko/deadbeef/blob/master/plugins/cocoaui/MainWindow.xib#L327 and https://github.com/Alexey-Yakovenko/deadbeef/blob/master/plugins/cocoaui/widgets/DdbTabStrip.m#L681)
> Add ability to copy(duplicate) a playlist

- plugins/cocoaui/DdbListview.h
- plugins/cocoaui/DdbListview.m
- plugins/cocoaui/DdbPlaylistViewController.m
Working dnd for playlist items, and external file drop.
Following the NSPasteboardReading and NSPasteboardWriting protocols for DnD.
> cocoaui: Working dnd

- deadbeef.desktop.in
> Add zh_CN localization into deadbeef.desktop.in

- plugins/gtkui/plcommon.c
I have not been able to test this against all GTK themes but results look identical to the old code on my system.
> gtkui: don't use pango's alpha attributes

- plugins/gtkui/ddblistview.c
- plugins/gtkui/ddblistview.h
- plugins/gtkui/mainplaylist.c
- plugins/gtkui/plcommon.c
- plugins/gtkui/plcommon.h
- plugins/gtkui/search.c
This is neccessary for correct rendering since idx argument doesn't take groups into account.
And first item of every group is always odd.
> gtkui: add even argument to column data draw functions

- junklib.c
> junklib: integrate the USLT tag with trkproperties

- plugins/hotkeys/actionhandlers.c
- plugins/hotkeys/actionhandlers.h
- plugins/hotkeys/hotkeys.c
This option adds or removes song(s) from playback queue. If they are already present in queue, they will be removed. This will close #942.
> hotkeys: Add "Add/Remove From Playback Queue" option

- shared/cueutil.c
- shared/cueutil.h
http://pastebin.com/raw/FrnVan7D
https://www.gnu.org/software/ccd2cue/manual/html_node/ISRC-_0028CUE-Command_0029.html#ISRC-_0028CUE-Command_0029
> cue: ISRC only applies to the current track

- plugins/cocoaui/DdbListview.m
Added visual line indicator for dnd drops.
A bit buggy when the list is grouped. Example: line is not viewed when group only has one element. line is not shown in first element of grouped list.
> cocoaui: dnd visual line indicator

- cueutil.c
- playlist.c
- plugins/gtkui/callbacks.h
- plugins/gtkui/deadbeef.glade
- plugins/gtkui/interface.c
- plugins/gtkui/prefwin.c
This reverts commit c531bf35f340975929a953db0fc85f2f63181158.
> Revert "support showing subindexes as separate tracks in playlist"

- po/zh_CN.po
> Chinese Po File Translation completion

- plugins/gtkui/support.h
- plugins/gtkui/widgets.c
There are many of them, but I've tried to make one first. I hope you like it.
> Fixed GTK3 warning

- plugins/converter/convgui.c
- plugins/gtkui/ddbtabstrip.c
- plugins/gtkui/eq.c
- plugins/gtkui/plcommon.c
- plugins/gtkui/trkproperties.c
- plugins/gtkui/widgets.c
- plugins/pltbrowser/pltbrowser.c
This resolves popup menu positioning on Wayland.
> gtkui: another round of transient-for fixes

- plugins/artwork-legacy/artwork.c
Example: path:/home/user/music/Queen/Innuendo, mask:covers/front*.jpg
> artwork: added relative path support in the image mask

- plugins/gtkui/gtkui.c
Here is a possible bugfix for #2231 that restores the old behavior for Gtk3. With my older local copy it works fine. However, the current Git version has a problem and cannot remember the correct position of the window if you click on the tray icon several times. This is not due to my submitted patch because this behavior can be observed even before when you revert to a previous state. There must have been a change that caused this, because it still works in 1.82.
> Bugfix for #2231

- plugins/gtkui/actionhandlers.c
- plugins/gtkui/callbacks.c
- plugins/gtkui/callbacks.h
- plugins/gtkui/deadbeef.glade
- plugins/gtkui/gtkui.c
- plugins/gtkui/interface.c
- plugins/gtkui/prefwin.c
Improved Remove From Disk routine 
* The warning dialog no longer shows a standard message, it shows what will be deleted 
* Deleted songs will be removed from all other playlists as well
* If desired the next song will be played when the currently played song is deleted (respects playback mode and play queue)
* Behavior is adjustable in the GUI (switched off by default)
> Better Remove From Disk

- plugins/gtkui/pltmenu.c
"Ask before removing a playlist" issue https://github.com/DeaDBeeF-Player/deadbeef/issues/1974
> Improved remove playlist feature

- plugins/artwork-legacy/cache.c
- plugins/vfs_curl/vfs_curl.c
- scripts/windows_postbuild.sh
- shared/windows/utils.c
- artwork: fix cache path generation for some builds
- windows: include and use certs for vfs_curl (fixes last.fm cover loading for artwork plugin)
> artwork: more updates

- plugins/gtkui/fileman.c
This patch never landed in the Windows branch so I'm sending it in now.
> gtkui: fix file filter for the GtkFileChooserNative implementation

- plugins/gtkui/gtkui.c
- plugins/gtkui/widgets.c
This fixes issue where scroll changes in response
to resizing the log window. Hooking the value-changed
signal of the GtkAdjustment is better as it only
triggers when users directly scroll.
> gtkui: fix logwindow/widget scroll detection

- plugins/gtkui/widgets.c
> gtkui: add parent menu for widgets

- plugins/gtkui/gtkui.c
> gtkui: Update titlebar based on TF update interval

- premake5-tools.lua
- premake5.lua
My travis build didn't run because I have now negative credit balance ... hope it compiles fine :smiley:
> premake script update

- plugins/hotkeys/actionhandlers.c
- plugins/hotkeys/actionhandlers.h
- plugins/hotkeys/hotkeys.c
> hotkeys: Previous or restart current rack action

- plugins/gtkui/actionhandlers.c
- plugins/gtkui/actionhandlers.h
- plugins/gtkui/gtkui.c
- plugins/gtkui/gtkui.h
- plugins/gtkui/pltmenu.c
- plugins/pltbrowser/pltbrowser.c
- translation/plugins.c
This allow us to assign a hotkey to rename the current playlist.
Some questions:
- Should we remove the commented out code in pltbrowser.c?
- How do best DRY up this? Most of the code comes from pltmenu.c
> add action_rename_current_playlist

- plugins/gtkui/pltmenu.c
wyt?
Should we do it for other than gtk?
> gtkui: Don't confirm remove playlist if empty

- plugins/gtkui/callbacks.c
- plugins/gtkui/callbacks.h
- plugins/gtkui/deadbeef.glade
- plugins/gtkui/interface.c
- plugins/gtkui/prefwin.c
also add option to filter by configurable plugins
> gtkui: sorth plugin list alphabetically

- plugins/sndfile/sndfile.c
This add *reading* support of RIFF tags for sndfile.
This is a partial solution of #1201.
> sndfile: inital support of RIFF tags.

- plugins/gtkui/plcommon.c
Implements an option to add a selection within the playlist to the front of the playback queue.
> gtkui: 'Add To Front Of Playback Queue' option in right-click dialog

- plugins/cocoaui/EditColumnWindowController.h
- plugins/cocoaui/EditColumnWindowController.m
- plugins/cocoaui/Playlist/PlaylistViewController.h
- plugins/cocoaui/Playlist/PlaylistViewController.m
Implement left, center and right alignment for text in playlist cells.
> Implement column alignment for cocoaui on medialib branch

- plugins/opus/opus.c
Implementation decoder2 API to support 64bit seek function in OPUS plugin.
Related to #2636
> Update OPUS plugin to implement decoder2 API

- plugins/ffmpeg/ffmpeg.c
Implementation decoder2 API to support 64bit seek function in ffmpeg plugin.
Related to #2636
> Updated ffmpeg plugin to implement decoder2 API

- plugins/gtkui/ddbvolumebar.c
- plugins/gtkui/ddbvolumebar.h
- plugins/gtkui/widgets.c
Now you can right click the volume bar widget in design mode and pick the scale you want.
> gtkui: implement scale property for DdbVolumeBar

- plugins/gtkui/ddbtabstrip.c
- Simplify text drawing code
- Use selected tab text color on hover
- Correct positioning to be in line with arrow buttons.
> gtkui: add new playlist button tweaks

- plugins/gtkui/playlist/ddblistview.c
Fixes very long subgroup titles being truncated way sooner than they should be. Also fixes a couple other small issues around subgroup titles, including proper truncation when artwork is positioned on the right of the playlist and fixing horizontal scrolling not scrolling subgroup headers.
> gtkui: fix subgroup titles being truncated at the wrong width

- plugins/gtkui/actionhandlers.c
- plugins/gtkui/callbacks.c
- plugins/gtkui/callbacks.h
- plugins/gtkui/deadbeef.glade
- plugins/gtkui/interface.c
> gtkui: improve sort by custom dialog
