plugins/gtkui/widgets.c, plugins/pltbrowser/pltbrowser.c
The patch in selproperties addresses a performance issue when the selection properties widget is visible and the DB_EV_SELCHANGED event is fired to often (e.g. when holding shift and cursor-up or down in playlist).
Playlistbrowser:
- I made the columns configurable and added an duration column showing the total duration of the playlist. Both items and duration column are disabled by default and can be enabled in a popup menu by right-clicking on the header.
- Highlighting the current playlist adds "(playing)" at the end of the active playlist. This is disabled by default.
- Middle mouse button on playlist closes playlist. (disabled by default)
- middle mouse button and double click with left mouse button on empty area opens new playlist, didn't feel the need to make that configurable but …
=> pltbrowser: add more mouse support, make columns configurable, add duration column, hightlight current playlist

plugins/pltbrowser/pltbrowser.c
I couldn't find a nice and reliable way to do the column sorting with gtk's sortable interface so I went with a slightly different approach where I sort the playlists on column click and  then update the treeview. Hope that's ok.
=> pltbrowser: add sorting when clicking column header and fix manual sorting with dnd

plugins/gtkui/ddblistview.c, plugins/gtkui/ddblistview.h, plugins/gtkui/mainplaylist.c, plugins/gtkui/plcommon.c, plugins/gtkui/plcommon.h, plugins/gtkui/search.c, plugins/gtkui/widgets.c
Goals of album art refactoring:
- get rid of too long argument lists
- reduce length of draw_column_data
- remove unnecessary variables
- avoid code duplication (cairo_rectangle calls)
=> Refactor album art drawing in listview and expand tabs in gtk3 ui

main.c
This would allow to use plugins in environments such as Nix/NixOS. Nix package manager places packages into separated immutable directories, so we can't add any plugins to the deadbeef installation prefix. Usual way to deal with this is to pass path to the plugins in an environment variable.
=> Read plugins dir from DEADBEEF_PLUGIN_DIR if available

plugins/gtkui/coverart.c, plugins/gtkui/coverart.h, plugins/gtkui/widgets.c
See bug #1200.  This pull request fixes the large widget scaling.  It allows requesting cover art by both height and width, to avoid the problem of not knowing what scaling to use without knowing the image dimensions and not knowing the image dimensions until the file has been loaded.  There is no change to the external API, although maybe the new call could be exposed.
=> Fix widget artwork scaling for non-square images

plugins/adplug/Makefile.am, plugins/gme/Makefile.am, plugins/sid/Makefile.am, plugins/supereq/Makefile.am
"cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++
but not for C"
=> emit compile warning

plugins/gtkui/coverart.c, plugins/gtkui/coverart.h, plugins/gtkui/ddblistview.c, plugins/gtkui/ddblistview.h, plugins/gtkui/mainplaylist.c, plugins/gtkui/plcommon.c, plugins/gtkui/plcommon.h, plugins/gtkui/search.c, plugins/gtkui/widgets.c
Fix playlist artwork sizing (issue #1200).
Fix memory leak, GTK assertions, and possible crash when removing coverart widget during a load.
Support multiple album art columns with different widths.
Fix column type in edit dialog (tf changes).
Fix column minheight calculations to allow for padding (and potentially more complex calculations).
Fix a number of deprecation warnings (playqueue, GTK3 gtk_paint_*, gdk_window_get_pointer, gdk_cairo_set_source_color).
Add clip region to GTK3 draw event calls and make more use of the clip region.
Fix native themed column headers.
Fix pinned header exposes (issue #1301)
=> Playlist artwork and rendering changes

plugins/gtkui/ddblistview.c
Fix header redraw when sizing after horizontal scrolling (issue #1308)
Work round horizontal scrollbar drawing artefact in GTK2 (issue #1308)
Fix scrolling to bottom of playlist momentarily while paging up (issue #1310)
Change scroll steps to be consistent horizontally and vertically, and when using a wheel over the drawing area or scrollbar (issue #1307)
Fingers crossed, caught up and merged all my changes.
=>  gtkui: fix playlist header redraw after resize, fix horizontal scrolllbar misdraw, change scrolling steps

plugins/gtkui/ddblistview.c, plugins/gtkui/ddblistview.h, plugins/gtkui/plcommon.c
Clip column text so that the ellipsis cannot overflow a column or header (issue #1306).
Abstract treeview background rendering to confine all the #ifdefs to one function (issue #1318 about transparent backgrounds is not fixed yet).
Make GTK3 styling for dragged headers more button-like.  They are styled like default buttons (not true column header buttons), pre-lit and focused, which is about the strongest button styling available in most themes.  In GTK2 the dragged headers still have the flat "selected" colouring.  Non-dragged buttons are still flat using the override colours.
=> Playlist column clipping, abstract treeview rendering and button styling

plugins/gtkui/ddblistview.c, plugins/gtkui/search.c
This is all the scrolling and clipping updates to support scrolling using gdk_window_scroll().
It also includes code to improve rendering when some theme elements are transparent.
=> gtkui: faster scrolling with gdk_window_scroll, improve drawng with theme transparency

plugins/gtkui/prefwin.c
This is part of a fix for issue #1354.  This PR blocks signals firing on certain widgets when they are initialised during creation of the dialog.  I have done this for all widgets which cause playlist refresh by sending CONFIGCHANGED or PLAYLISTCHANGED messages.  It should probably be done for all widgets in the dialog that would fire signals.
=> prefwin: block signals when initialising dialog

plugins/gtkui/ddbtabstrip.c
A double click on a playlist tab starts playback for that list. The
previous cursor position will determines the track to be played.
This patch implements #507
=> gtkui: Double click on plt tab starts playback

sort.c
On a playlist sort the cursor now sticks to the track not the position.
This fixes issue #1370.
=> Keep cursor position on playlist sort.

plugins/gtkui/ddblistview.c, plugins/gtkui/widgets.c
Fix a small error when group selections are toggled (eg. ctrl-click on album art), the wrong rows are redrawn.  This was hidden by all rows that are selected or de-selected being redrawn a second time, also fixed.
=> gtkui: fix drawing wrong row when toggling a group selection, and don't do duplicate draws for row selection changes

plugins/gtkui/ddblistview.c, plugins/gtkui/ddblistview.h, plugins/gtkui/drawing.h, plugins/gtkui/gdkdrawing.c, plugins/gtkui/mainplaylist.c, plugins/gtkui/plcommon.c, plugins/gtkui/plcommon.h, plugins/gtkui/search.c
Common practice for data lists with text content that is truncated is to provide a tooltip showing the entire text.  This PR does that both for the listview rows and for the column headers.
Previous code for potentially showing the track URI as the tooltip, in response to a dummy config value and only on the main playlist, is completely removed.
=> gtkui: add listview tooltips for columns and headers which are truncated

plugins/gtkui/trkproperties.c
I think this was done once, but it isn't working now.
=> gtkui: (re)fix trkproperties to allow the deletion of fields longer than 4,999 characters

playlist.c
Selected search items are also cleared inside plt_search_reset_int(), so pass the flag in there.
=> playlist: only clear existing selection in plt_search_process2 if requested

plugins/gtkui/ddblistview.c, plugins/gtkui/drawing.h, plugins/gtkui/gdkdrawing.c, plugins/gtkui/plcommon.c, plugins/libparser/parser.c, plugins/libparser/parser.h
This is to fix issue #1381.  The extent of text was incorrectly calculated, especially with leading or trailing whitespace.
It also preserves leading and trailing whitespace in group formats  At the moment, it is saved for a while, then lost on restart.
=> Text drawing changes

plugins/gtkui/plcommon.c, tf.c
%album artist% in foobar2000 works like that:
>%album artist%: Name of the artist of the album specified track belongs to. Checks following metadata fields, in this order: "album artist", "artist", "composer", "performer".
=> Make %album artist% more consistent with foobar2000 and remove some gtk warnings

plugins/cocoaui/deadbeef-Info.plist, plugins/converter/converter.c
This removes the define for '/usr/local/bin/' encoder path in OSX. 
Execution of encoders now relies only in the PATH env variable when no full path is given (like in Linux). Set PATH variable value in LSEnvironment,deadbeef-Info.plist to '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin' (if no value is set, the default is '/usr/bin:/bin:/usr/sbin:/sbin'). This is only applicable when launched through Launch Services. If executed directly from the command line the env variables of the shell are used and the LSEnvironmnt dictionary is ignored.
This last part is also applicable to Xcode. When running in Xcode the path variable must be set in the schema preferences.
https://developer.apple.com/library/mac/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//ap …
=> osx: Removing define for '/usr/local/bin/' encoder path in OSX.

plugins/cocoaui/deadbeef-Info.plist
Pull request for filetype association configuration in the plist.info file.
PS: The LSEnvironment key position change was done automatically by Xcode.
=> Associated deadbeef with the currently supported filetypes. (osx/cocoaui build)

plugins/gtkui/Makefile.am, plugins/gtkui/ddb_splitter.c, plugins/gtkui/ddb_splitter.h, plugins/gtkui/ddb_splitter_size_mode.c, plugins/gtkui/ddb_splitter_size_mode.h, plugins/gtkui/widgets.c
This pull request adds a new container widget (DdbSplitter, similar to GtkPaned) to the gtkui that's now used internally by the horizontal and vertical splitter (instead of GtkPaned and GtkBox). It works similar to the foobar2000 splitter widget.
The splitter widget now has the following config entries:
- `locked`
- `0`: proportional scaling
- `1`: lock size of first child
- `2`: lock size of second child (new)
- `prop` (new)
- `float_value` `[0.0, 1.0]`: the proportion value used in proportional scaling
- `size_c1` (new)
- the size of the first child, this is the same as the old `pos` value and used to determine the size when child 1 is locked
- `size_c2` (new)
- the size of the second child, used when child 2 is locked
The container has the following features:
- ability to hold up to …
=> gtkui: add new splitter widget

plugins/gtkui/Makefile.am, plugins/gtkui/clipboard.c, plugins/gtkui/clipboard.h, plugins/gtkui/ddblistview.c, plugins/gtkui/ddblistview.h, plugins/gtkui/gtkui.c, plugins/gtkui/gtkui_api.h, plugins/gtkui/mainplaylist.c, plugins/gtkui/plcommon.c, plugins/gtkui/plcommon.h, plugins/gtkui/pltmenu.c, plugins/gtkui/search.c, plugins/pltbrowser/pltbrowser.c
This is quite a big patch so I don't expect it to get merged right away.
What this PR does: It adds copy, cut and paste support to the ddblistview, the pltbrowser and the pltmenu. C&P works both from DeaDBeeF to file managers and the other way around, and of course within DeaDBeeF (copy track(s) in playlist1 and paste it/them in playlist2). Pasting tracks to the pltbrowser first creates a new playlist and then pastes the tracks there. C&P can be triggered either via menu items or via shortcuts (ctrl+c, ctrl+x, ctrl+v).
To make C&P available to the pltbrowser plugin I added an API to the gtkui plugin:
https://github.com/Alexey-Yakovenko/deadbeef/compare/master...cboxdoerfer:copy_paste?expand=1#diff-31721c7ad41dcfea0c8abdd8072c53e9R263
Hope I can get any feedback on that. I also thought …
=> gtkui: add copy/paste support

plugins/gtkui/callbacks.c, plugins/gtkui/pltmenu.c, plugins/gtkui/widgets.c, plugins/pltbrowser/pltbrowser.c
=> Fix some untranslateable strings and use more consistent naming in Rename Tab and Playlist dialogs

junklib.c
a crash caused by referencing a variable that goes out of scope.
=> junklib: Fix for strict aliasing in compilation, prevents

plugins/cdda/cdda.c
Make sure that the sector counter is always incremented after a sector is read, fixes issue #1613.
=> cdda: fix error in sector counting after seek

plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c
Now when you resize the dialog all the extra space is added to the group by entry.
=> gtkui: don't expand help link widget in group by dialog

plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c
Same patch as before, just for the add/edit column dialog.
=> gtkui: don't expand help link widget in add/edit column dialog

deadbeef.h, logger.c, logger.h, plugins.c
This would allow more convenient integration with existing code that already uses variable arguments functions.
Compile checked on Linux, should I add some tests?
I've found this line in existing code suspicious a bit:
> (void) vsnprintf(text, 128, fmt, ap);
What is 128? Was it meant to be sizeof (text)?
=> deadbeef.h: add logging api with va_list parameters

plugins/gtkui/callbacks.c, plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c, plugins/gtkui/plcommon.c, plugins/gtkui/plcommon.h
This adds the `year` as an option of the column drop down for when users wants to add additional columns.
When I first started looking into this, I was unsure how I could add the Year to a column as it wasn't under the pre-populated list -- I now know that I could have just entered `%year%`. Nonetheless, maybe some other users have been confused about this -- now one can simply select `year` from the drop down.
Thanks,
Alex
=> add year to column dropdown options

junklib.c
Function `junk_add_disc_meta` was defined, but not used for APEv2 tags. Tested on wavepack files, works.
=> junklib: split disc into disc/number for APEv2 tags

deadbeef.desktop.in
The issues were discovered by `desktop-file-validate` utility from the _desktop-file-utils_ package.
One issue still remains though:
```
deadbeef.desktop.in: error: file contains group "Play Shortcut Group", but groups extending the format should start with "X-"
deadbeef.desktop.in: error: file contains group "Pause Shortcut Group", but groups extending the format should start with "X-"
deadbeef.desktop.in: error: file contains group "Stop Shortcut Group", but groups extending the format should start with "X-"
deadbeef.desktop.in: error: file contains group "Next Shortcut Group", but groups extending the format should start with "X-"
deadbeef.desktop.in: error: file contains group "Prev Shortcut Group", but groups extending the format should start with "X-"
```
which is caused by …
=> fix and enhance deadbeef.desktop.in

plugins/gme/game-music-emu-0.6pre/gme/blargg_endian.h
Currently blargg_endian fails to detect endiness on non-x86, as ppc64le,
when not using glibc.
In my case, I am using musl on ppc64le, and deadbeef fails to compile
because the endianess is not known.
This patch check if the macros are defined before using it, other than
checking for GLIBC.
=> blargg_endian: Fails to build on non-x86 with musl

playlist.c
SONGWRITER – Per-disc or per-track songwriter name for CD-Text data.
http://wiki.hydrogenaud.io/index.php?title=Cue_sheet#Cue_sheet_commands
=> support SONGWRITER tag in cue sheet (closes #844)

plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c
The vertical separator was expanding leaving a huge gray area when resizing the preference dialog on GTK3.
=> gtkui: fix vertical separator in preference dialog

playlist.c
It's in the cdrwin manual.. and foobar2000 parses this cuesheet correctly
(while deadbeef does not):
catalog ABCD
isrc 81237475
rem genre classical
rem date 1991
rem discid 860B6S0A
rem comment "ExactAudioCopy v0.95b4"
rem composer "composer"
rem totaldiscs 1
rem discnumber 1
performer "PPPP"
songwriter "AAA"
title "MMM"
file "aaa.mp3" WAVE
track 01 audio
title "track 2"
performer "P1"
index 01 00:00:00
track 02 audio
title "track 2"
performer "P2"
index 01 01:00:00
=> Cuesheet commands are not case sensitive

plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c, plugins/gtkui/mainplaylist.c, plugins/gtkui/plcommon.c, plugins/gtkui/plcommon.h, plugins/gtkui/search.c
This adds a new text entry below Format in columns add/edit dialog. If non-empty it will be used for sorting instead of the display format.
=> gtkui: add sort format to columns

deadbeef.h, plugins/gtkui/callbacks.c, plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c, plugins/gtkui/mainplaylist.c, plugins/gtkui/plcommon.c, plugins/gtkui/plcommon.h, plugins/gtkui/search.c
This makes adding/removing/rearranging the preset column types more manageable.
It also prepares the code if we want to make this user configurable in the future.
=> gtkui: refactor preset column types code

plugins/pltbrowser/pltbrowser.c
Allow users to disable changing playlist with doubleclick in playlist browser.
=> pltbrowser: add option to disable double-click playlist switch

plugins/gtkui/hotkeys.c
Use Alt+Return hotkey to open Track properties by default. This closes #1522 .
=> gtkui: add hotkey for track properties

Makefile.am, configure.ac, deadbeef.h, playlist.c, playlist.h, plugins.c, plugins/cue/COPYING, plugins/cue/Makefile.am, plugins/cue/cue.c, shared/cueutil.c, shared/cueutil.h
I've had this code for a while and thought i should open a pull request before it gets lost..
This adds support for opnening *.cue files directly.
With this plugin cue support can be considered complete (in a basic level, because i remember seeing foobar2000 do advanced stuff even with tracks+cue stuff).
Features:
- tracks+cue  support (tags + replaygain, lacking everything else)
- cdimage+cue support (new api (hacks)* to get playlist.c do the required stuff..)
plt_set_cue_file(const char *filename)
plt_unset_cue_file(void)
There's also the ability to save playlists in cue format, but it's disabled.
It can be enabled if the auto totaltracks stuff is removed.. but i'm not sure.
cdimage+cue
------------
If only 1 file is detected then:
- set the internal deadbeef cue_file variable
- insert …
=> add cue playlist plugin (tracks/cdimage+cue support)

playlist.c, plugins/gtkui/callbacks.h, plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c, plugins/gtkui/prefwin.c, shared/cueutil.c, shared/cueutil.h
https://pastebin.com/raw/PRuTEkGz
cuesheets from some CDs ripped with EAC might have
TRACK "01" AUDIO
TITLE "title"
INDEX 01 00:00:00
INDEX 02 01:30:00
INDEX 03 02:00:00
INDEX 04 02:49:00
etc..
INDEX 02+ are ignored by basically every player i tried, including fb2k.
Mostly found in OSTs and symphonic/progressive stuff.
(http://forums.stevehoffman.tv/threads/question-about-song-indexing-in-older-maybe-newer-cd-players.253955/)
These extra indexes or "subindexes" usually describe a new section, a different melody... another "track" within the same track.. !
There's a new setting "cue.subindexes_as_tracks" and a gtkui checkbox to enable or disable it (it's disabled by default).
Menu Edit-> Preferences-> GUI/Misc -> Playlist-> CUE: show subindexes as tracks...
If it's enabled and one of those …
=> (cdimage+cue) support showing subindexes as separate tracks in playlist

configure.ac, plugins/gtkui/Makefile.am, plugins/gtkui/deadbeefapp.c, plugins/gtkui/deadbeefapp.h, plugins/gtkui/gtk/menus.ui, plugins/gtkui/gtkui.c, plugins/gtkui/gtkui.gresources.xml, plugins/gtkui/gtkui.h, plugins/gtkui/progress.c, travis/build.sh
This changes the GTK3 implementation to use a application class based on GtkApplication.
First primary benefit of this is to get access to appmenu functionality which is also implemented with this change.
Second is progress dialog now indicates to desktop shell that the app is busy. e.g Gnome-shell will display a spinner next to the application name in the top bar.
This also cleans up the GTK2 parts of the code. Calling gdk_threads_enter/leave is no longer necessary since DeaDBeeF now runs GTK+ in the main thread.
=> gtkui: use GtkApplication model

plugins/gtkui/ddblistview.c
Selected background color ended up being rendered all over the playlist widget area. This PR fixes that.
Only noticed it when testing under Ubuntu 14.04.
=> gtkui: fix background rendering of playlist rows on GTK3

plugins/hotkeys/actionhandlers.c, plugins/hotkeys/actionhandlers.h, plugins/hotkeys/hotkeys.c
Adds option to move tracks with hotkeys. Works with selection and nowplaying. Has no action for whole playlist (obviously).
I had some problems with understanding how `plt_move_items()` works but I hope I got it right.
I think it would close #1667. Eventually I can add Ctrl+Alt+Up and Ctrl+Alt+Down as default keys for moving songs.
=> hotkeys: add "move tracks up/down" option

.travis.yml
This will ensure that cloned deadbeef repos will include sudo which is missing by default.
=> travis: require sudo for linux build

plugins/cdda/cdda.c
Some versions of cdio does not convert and return strings in UTF-8. If that's the case, convert the strings to UTF-8 manually.
=> cdda: convert cd text if it's not UTF-8

main.c
My goal was to get rid of confusing `#ifdef PORTABLE` blocks and have one code for all versions. Additionally it searches now for `config/` directory to detect PORTABLE_FULL build.
=> main: rework directory search

main.c
When deadbeef is installed and run with `deadbeef` it will fail, because it can't find path it was run from.
On linux it's possible to read executable location through `readlink("/proc/self/exe", buf, bufsize)` I don't know if you want it or not through.
=> main: fix when executable in path

plugins/cocoaui/DdbListview.m, plugins/cocoaui/DdbShared.h, plugins/cocoaui/DdbShared.m, plugins/cocoaui/widgets/DdbTabStrip.m
- You can d'n'd to a different playlist. Tab will get selected if you drag over it.
- Same behaviour between internal and external drops, that is, all will be added before the selected row, if any, or at the end of the playlist if none selected.
Visual indicator is still needed.
=> More work on dnd in the CocoaUI

deadbeef.h, playlist.c, playlist.h
=> rename start/end sample variables back to 0.7.2 names to avoid breaking API

streamer.c
I just wanted to get the ball rolling on this.
Turns out there is no guarantee that `st` is always `OUTPUT_STATE_PAUSED` here if not playing which means that `DB_EV_PAUSED` is not signalled which breaks certain things like the spectrum vis which then doesn't start drawing on playback. Even if something externally doesn't rely on just `DB_EV_PAUSE` events like musical sprectrum which also hooks `DB_EV_STOP` it seems to fail to start the vis when deadbeef resumes playback on startup. This quick fix resolves those issues for me.
=> streamer: fix signalling of DB_EV_PAUSED

plugins/gtkui/gtkui.c
this is to account for the client side decoration added by my headerbar plugin so window is positioned correctly
it also makes more sense to have this right before gtk_widget_show
=> gtkui: move wingeom_restore call after window_init_hooks

plugins/gtkui/deadbeefapp.c
activate handler can be called via DBus so don't create mainwin here
=> gtkui: Ensure single-instance

Makefile.am
Fixes the following issue with `make distcheck`.
```
Making check in po
make[2]: Entering directory '/tmp/deadbeef/deadbeef-devel/_build/sub/po'
make[2]: *** No rule to make target '../../../translation/plugins.c', needed by 'deadbeef.pot'.  Stop.
make[2]: Leaving directory '/tmp/deadbeef/deadbeef-devel/_build/sub/po'
make[1]: *** [Makefile:906: check-recursive] Error 1
make[1]: Leaving directory '/tmp/deadbeef/deadbeef-devel/_build/sub'
make: *** [Makefile:1119: distcheck] Error 1
```
Now `distcheck` succeeds for me.
=> Makefile.am: Fix distcheck.

junklib.c, plugins/aac/aac.c, plugins/adplug/adplug-db.cpp, plugins/alac/alac_plugin.c, plugins/dca/dcaplug.c, plugins/dumb/cdumb.c, plugins/ffap/ffap.c, plugins/flac/flac.c, plugins/gme/cgme.c, plugins/mp3/mp3.c, plugins/musepack/musepack.c, plugins/opus/opus.c, plugins/psf/plugin.c, plugins/sc68/in_sc68.c, plugins/shn/shn.c, plugins/sid/csid.cpp, plugins/sndfile/sndfile.c, plugins/tta/ttaplug.c, plugins/vorbis/vorbis.c, plugins/vtx/vtx.c, plugins/wavpack/wavpack.c, plugins/wildmidi/wildmidiplug.c, shared/mp4tagutil.c, strdupa.h
fix #2034 
I have a question, why WMA (and v2m) decoder doesn't use pl_lock when calling pl_find_meta function while the others do?
=> Move fopen out of pl_lock in decoders

plugins/gtkui/ddblistview.c, plugins/gtkui/ddblistview.h, plugins/gtkui/mainplaylist.c, plugins/gtkui/plcommon.c, plugins/gtkui/plcommon.h, plugins/gtkui/search.c
This is a first pass at implementing #1145. It allows for an arbitrary number of nested groups and allows for formats that allow for groups with empty/invisible titles.
Current Implementation List:
These two will be in a future PR:
- Change the way subgroups are stored in preferences to allow for unique TF sequences per group, not using a delimiting token.
- Make a new "Group By" dialog exposing the new functionality.
Questions:
- ~~How do we want to store subgroups in settings? Right now I pack it into the normal group setting and use a pipe `|` to separate them.~~ **This will be changed to store them as unique strings in settings in a future PR. For the time being, `|||` will be used instead.**
- ~~How do we want pinning to function? Does it pin every subgroup, or only the top-level …
=> Implement subgroups for GTK

plugins/alsa/alsa.c
it's only reached when setting the format fails but at least the player doesn't freeze when that happens now
=> alsa: fix a missing mutex unlock

plugins/gtkui/ddblistview.c, plugins/gtkui/ddblistview.h, plugins/gtkui/plcommon.c
A small bug that slipped through the cracks in #2044. When scrolling through a playlist with arrow keys, the playlist scrolling doesn't take the height of nested subgroup labels into account, sometimes hiding the selected track under a pinned label. This fixes the bug by making the whole height of all the subgroups into account for calculating the scroll position.
=> Fix scrolling with arrow keys with pinned nested subgroups

plugins/gtkui/plcommon.c
I scanned the code base with the tool [cppcheck](http://cppcheck.sourceforge.net/), and I discovered one interesting finding:
```
[gtkui/plcommon.c:1311]: (error) Dereferencing 'fmt' after it is deallocated / released
```
Given that a local variable was already declared and pointing to the next element, I assume this dereference is a small mistake that is easily corrected.
=> Fix use-after-free bug

junklib.c, plugins/flac/flac.c, plugins/vorbis/vorbis.c, shared/mp4tagutil.c
Not all ReplayGain tags are written correctly.
* `REPLAYGAIN_*_GAIN` tags should have two decimal places and have a " dB" suffix.
* `REPLAYGAIN_*_PEAK` tags should have six decimal places.
* Tag keys should be all uppercase.
https://wiki.hydrogenaud.io/index.php?title=ReplayGain_2.0_specification#Metadata_format
=> flac/junklib/vorbis/mp4tagutil: format replaygain tags correctly

plugins/gtkui/plcommon.c
Fixes tall album art being lower quality.
Before:
After:
=> gtkui: scale album art to largest dimension

plugins/gtkui/plcommon.c
Fixes regression caused by #2135
I noticed some album art was causing big performance regressions with the latest change. This change fixes those regressions and still keeps the better image quality for tall images.
=> gtkui: Fix performance regression with some tall album art images

plugins/gtkui/plcommon.c
This is only an issue in some environments where you have deadbeef installed but not shared resources but I ran into it doing debugging. These checks prevent huge playlist corruption when trying to draw said bitmaps.
=> gtkui: Fix errors when certain playlist bitmaps are missing.

tf.c
The playback_time_ms keyword can be used with the ddb_playback_status plugin to display playback position in a higher resolution.
=> Add playback_time_ms title format keyword

osx/Tests/TitleFormattingTests.m, tf.c
This follows on from #2190.
- When the top level function fails, produce an empty string, like it would if it was a nested call.
- Adjust `$progress` to support and match fb2k's handling of zero-range calls, such as `$progress(0,0,10,x,=)`
- Adds a test to track support of complicated function chains.
=> Title formatting, Part 2

plugins/converter/callbacks.h, plugins/gtkui/callbacks.c, plugins/gtkui/callbacks.h, plugins/gtkui/deadbeef.glade, plugins/gtkui/gtkui.c, plugins/gtkui/gtkui.h, plugins/gtkui/interface.c, plugins/gtkui/prefwin.c, plugins/gtkui/widgets.c
This is a pull request for a better start minimized to tray.
The following things have been improved:
* the main window is no longer displayed and then hidden
* no more high CPU load if the main window was not switched to visible before (caused by init_widget_layout ();)
* no endless error messages GDK_IS_WINDOW (window)' failed errors (caused by update_songinfo (gpointer unused))
* shutdown of the application has also been reviewed and modified
* start minimized to tray can now be configured in the settings
* a check has been added that "minimized to tray" and "trayicon invisible" cannot be enabled both
=> Start minimized to tray

osx/Tests/TitleFormattingTests.m, tf.c
This is a fix for #2197.
It's pretty trivial, however, there is some difficulty with relative paths that also may be stored in :URI metadata record. I decided to format them as non-standard file URI extension, because the alternative is to call realpath() to convert relative paths to absolute, and it is bad idea to do so in tf_eval() because it should be fast.
Maybe, it is a good idea not to store relative paths inside :URI at all by explicitly resolving them inside plt_insert_file_int(). It seems that foobar2000 is doing similar thing because for relative path provided through File->Add location it outputs absolute %_path_raw%. However, this is more intrusive change and it should be made per separate PR, if at all.
Please let me know what do you think on it.
I also wanted to add new …
=> Path raw fix

playlist.c
The displayed duration of songs is rounded internally, but not from selected songs. This can lead to different displayed values of individual files and of course cumulated values.
=> Values from selection_playback_time are not rounded

plugins/gtkui/gtkui.c, plugins/gtkui/rg.c, plugins/gtkui/rg.h
This Pull Request adds a new entry to the ReplayGain Scanner: Track Gain All Unscanned Files In Playlist.
It is not easy to see which files are replay gained and which are not. Especially in larger collections it quickly becomes chaotic. The new routine therefore checks all files in the current playlist to see if they have been replay gained, and only processes those that are not. This is fast and efficient.
=> Track Gain All Unscanned Files In Playlist

playlist.c, plugins.c
- Fixed order so that `is_relative_path` is called after conversion
- More structured approach of detection. It is not covering all the cases but I guess it will be fine. We could also consider using [`PathIsRelative()`](https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-pathisrelativea) from windows api
=> windows: is_relative_path fix for windows

streamer.c
the `scope` gui widget (and probably others) cause a segfault without this
might fix https://github.com/DeaDBeeF-Player/deadbeef/issues/2268
=> streamer: fix allocation size

plugins/gtkui/rg.c
* time calculation fixed  #2217
* info label now shows more detailed info "(%i of %i files)"
=> rg scanner: time calculation bug fixed

plugins/artwork-legacy/artwork.c
Currently, if none of the specified filenames (`*cover*.jpg`, `*cover*.png`, etc.) is found in local folder, DB falls back to any jpg/jpeg.
Add fallback to png as well.
Makes it consistent with 'artwork' plugin:
https://github.com/DeaDBeeF-Player/deadbeef/blob/master/plugins/artwork/artwork.c#L1254#L1256
=> artwork-legacy: add fallback to *.png

plugins/vfs_curl/vfs_curl.c
SHOUTcast server responds with "ICY 200 OK" (non-)http status
=> vfs_curl: SHOUTcast server support

deadbeef.h
line 1601 ends an enum declaration but it's missing the semicolon
```
% clang -xc -DDDB_API_LEVEL=10 /usr/include/deadbeef/deadbeef.h
/usr/include/deadbeef/deadbeef.h:1601:2: error: expected ';' after enum
}
^
;
```
=> fix syntax error in deadbeef.h

tf.c
Hi,
This PR adds support for the `last_modified` title format keyword, using the format specified in [Foobar2000:Title Formatting Reference](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#.25last_modified.25).
This functionality has been already requested via https://github.com/DeaDBeeF-Player/deadbeef/issues/1862 and https://github.com/DeaDBeeF-Player/deadbeef/issues/724.
Please note I've only tested on an Ubuntu 18.04 derivative (Linux Mint) since I don't have any other (non-Linux) development platform available right now!
Thank you!
=> Add last_modified title format keyword

plugins/libmp4ff/mp4ff.c
Some mp4 files cause Segmentation Fault without this check. Turns out that `mp4ff_get_decoder_config()` succeeds every time request is valid, but only sets buff and buff_size if these values are known.
=> alac: fix for no decoder config

playlist.c, plugins/portaudio/portaudio.c, plugins/shellexec/shellexecutil.c, premake5-tools.lua, premake5-win.lua, premake5.lua, shared/windows/fopen.c, shared/windows/mingw32_layer.h, shared/windows/mkdir.c, shared/windows/rename.c, shared/windows/rmdir.c, shared/windows/scandir.c, shared/windows/stat.c, shared/windows/strcasestr.c, shared/windows/strndup.c, shared/windows/utils.c, shared/windows/utils.h
Summary of the changes:
- portaudio stream drain fix (v1.6)
- title formatting v1 returns windows-converted directories (tf v1 only used in shellexec)
- shellexec on windows now runs commands in background + single quotation mark fix
- premake: added tta
- premake-win: added tta, shellexec (+gtk2/3)
- premake-tools: each run of premake-win generates version based on date
- shared/windows: licence fix
- shared/windows: add mkdir and rmdir implementations
=> Windows branch merge

.travis.yml, premake5-tools.lua, premake5-win.lua, tools/windows-installer/deadbeef.iss, travis/build.sh, travis/upload.sh
This PR adds windows build to travis, which builds same binaries as in "DeaDBeeF for Windows" project.
Build script downloads https://github.com/kuba160/deadbeef-windows-deps.git which contains GTK theme and icons used by default in "DeaDBeeF for Windows" project. I did not test travis builds yet, but I tested builds from GitHub Actions made by similar script and they were working fine. `upload.sh` was updated to support uploading windows builds to sourceforge. If there are some changes that can't be accepted please let me know.
=> Add windows build to travis

main.c, plugins/artwork-legacy/cache.c
- fix for double `deadbeef` in cache path
- move slash conversion to main program
- remove path generation from `HOMEDIR`, it is already done for `DDB_SYS_DIR_CACHE` in main
=> artwork small fixes

plugins/gtkui/actionhandlers.c, plugins/gtkui/callbacks.c, plugins/gtkui/callbacks.h, plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c, plugins/gtkui/prefwin.c
Instead of deleting files directly the files are moved to the recycle bin with [GIO](https://developer.gnome.org/gio/stable/gio.html) (if available, but should be present in all GTK based distributions).
=> Linux: Move files to trash

configure.ac, plugins/medialib/Makefile.am
Some changes to the autoconf scripts needed to be made and some Jannson build flags needed to be added to the plugin Makefile.
I have to note that I have to explicitly enable the plugin with `--enable-medialib` despite it looking like it should be detected automatically in the autoconf script.
=> medialib: get medialib building and running on Linux

.travis.yml, premake5-win.lua, scripts/windows_postbuild.sh, travis/build.sh
The idea is that you:
1. Fork [DeaDBeeF-for-Windows/xdispatch_ddb](https://github.com/DeaDBeeF-for-Windows/xdispatch_ddb) into DeaDBeeF-Player.
2. Travis compiles windows version of libdispatch (xdispatch)
3. Zip file with binaries and headers is being sent to deadbeef sourceforge to `staticdeps/ddb-xdispatch-win-latest.zip`
4. Deadbeef travis build script downloads that zip file, unpacks it and uses provided libdispatch with its headers for windows build.
Please let me know if there is something you would like to do differently. If not, please rerun the build after `staticdeps/ddb-xdispatch-win-latest.zip` is available on sourceforge servers.
=> medialib: windows clang support

plugins/aac/aac.c, plugins/alac/alac_plugin.c
This fixes the underlying issue causing the crash in https://github.com/DeaDBeeF-Player/deadbeef/issues/2466.
Also fixes a second leak that happened on each ALAC track playback.
=> Prevent leaking file descriptors when loading and playing ALAC files

main.c
This was accidentally reverted by commit 61c3bc88732ff1dd21a3e8fef706dede0d01df17
On Windows XDG_RUNTIME_DIR is unset so it will simply use the dbconfdir path.
=> main: Make socket path use XDG_RUNTIME_DIR if set again

plugins/gtkui/gtkui.c
This is determined at runtime when built against sufficiently new GTK+ so check if the action actually exist.
=> gtkui: Fix warning when there is no log action

junklib.c
Tested parsing both MP3 with ID3v2.3 and WavPack with APEv2 tags, and converting to and from files.
Technically the TSST frame is only in ID3v2.4, but at least foobar2000 supports them in ID3v2.3 tag mapping and MusicBrainz Picard adds them in ID3v2.3 tags: https://wiki.hydrogenaud.io/index.php?title=Foobar2000:ID3_Tag_Mapping
=> junklib: add support for disc subtitle tags in ID3 and APE tags

plugins/psf/eng_psf/eng_psf.c, plugins/psf/eng_psf/psx_hw.c, plugins/psf/psfmain.c
Fix getting a relative directory error on windows, which causes the file(such as .minidsf .minipsf .miniqsf .minissf) not to be imported
=> psf: fix getting a relative directory error on windows

plugins/gtkui/callbacks.h, plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c, plugins/gtkui/pluginconf.c, plugins/gtkui/pluginconf.h, plugins/gtkui/prefwin.c
Notes:
I had to change the code in `apply_conf` from using `lookup_widget` glade utility function to `g_object_get_data` directly as it needs to work with any container and not just top levels where it can find the outermost parent. `gtkui_run_dialog` expected a parent dialog passed to it which remains until none of the child objects are needed. I hope this change has no side effects this time.
=> gtkui: New plugin preferences UI

premake5.lua, scripts/windows_postbuild.sh
Fixes issues with symbols not exporting correctly on local build on windows.
=> premake5: export all symbols on windows

plugins/gtkui/actionhandlers.c, plugins/gtkui/gtkui.c, plugins/gtkui/gtkui.h, plugins/gtkui/pltmenu.c
I messed up a bit with my last pr. Now renames the right playlist
=> gtkui: fix rename the right plt_idx

tf.c
and remove unnecessary assignment
=> tf: ignore whitespace args to $rgb

plugins/sndfile/sndfile.c
Fix the memory leak and make it safer to call according to the pattern
in flac plugin.
=> sndfile: clean up sndfile_free.

scripts/windows_postbuild.sh
Fixes build failure caused by `ldd` update in msys2 repo.
I suggest to rerun open PR builds after merging this.
=> windows_postbuild: fix parsing for unresolved libs

plugins/artwork-legacy/artwork.c
These commits were sent as PR to DeaDBeeF-for-Windows by Keith. I told him it would be more appropriate to sent it straight here. It sadly never happened but now I'm doing this because I still think these changes are useful.
Please let me know what you think about these changes and request changes if necessary (`is_illegal_windows_name` could be rewritten for better readability for sure 🙂).
=> Sanitize paths for artwork-legacy

configure.ac
fixes build on systems where kqueue is not installed or required for libdispatch
=> do not explicitly link kqueue library for libdispatch

.gitignore, deadbeef.h, main.c, plugins/artwork-legacy/artwork.c
Fixes:
- Add premake build files into `.gitignore`
- Fix hardcoded wildcards in `artwork-legacy` (fixes #2494)
exec_cmdline:
- Runs in `server_exec_command_line`
- Gets plugins from `plug_get_list()` and calls `exec_cmdline` if implemented
- Calls every plugin even though some plugin might already have used and processed given arguments. I was unsure what 'right' behavior should be. There might be a case where some broken plugin can pretend to have used arguments and make other plugins not receive `exec_cmdline` calls. From other side this can lead to arguments being interpreted twice. Can change depending on your final opinion.
EDIT:
Proposal of implementation can be found here: https://gist.github.com/Alexey-Yakovenko/aa226803af604042721d671ecde94c3d
=> exec_cmdline implementation + small fixes

plugins/gtkui/ddbtabstrip.c
This makes left/right arrow captive and you must use TAB key to move
focus to next widget.
=> gtkui: fix keyboard nav on tabstrip

plugins/gtkui/ddblistview.c, plugins/gtkui/ddbtabstrip.c
This just makes sure listview headers match theme colors unless overridden.
get_tab_under_cursor will now check for arrows.
(I will do a PR with the remaining fixes for tabstrip later)
=> Listview header render code and get_tab_under_cursor fix

plugins/gtkui/actions.c
So menu items for plugin actions can be removed.
=> gtkui: Set plugaction object data again after refactoring

plugins/gtkui/covermanager/covermanager.c
Some albums purchased on Qobuz come with files larger than the current limit. The older artwork plugin displayed those files smoothly.  In addition, I guess this would make the file size more consistent with the 2048px hard-limit in `plugins/artwork/artwork.c`
As a practical test, with this increased size requirement, my 10'000 album arts all fit.
=> Increase by 4 the maximum album art file size

plugins/gtkui/actionhandlers.c, plugins/gtkui/gtkui.c, plugins/gtkui/gtkui.h, plugins/gtkui/pltmenu.c
Removing playlist from pltmenu or using an actionhandler would result
in different behavior. This commit makes sure that both paths asks for
confirmation before removing a playlist.
=> actionhandler ask for confirmation to remove playlist.

po/POTFILES.in
```make check``` produced the following error
```
Making check in po
make[1]: Entering directory '/tmp/deadbeef-1.9.2/po'
INTLTOOL_EXTRACT="/usr/bin/intltool-extract" XGETTEXT="/usr/bin/xgettext" srcdir=. /usr/bin/intltool-update --gettext-package deadbeef --pot
rm -f missing notexist
srcdir=. /usr/bin/intltool-update -m
The following files contain translations and are currently not in use. Please
consider adding these to the POTFILES.in file, located in the po/ directory.
plugins/gtkui/selpropertieswidget.c
If some of these files are left out on purpose then please add them to
POTFILES.skip instead of POTFILES.in. A file 'missing' containing this list
of left out files has been written in the current directory.
if [ -r missing -o -r notexist ]; then \
exit 1; \
fi
make[1]: *** …
```
=> Fix "make check" failed

plugins/ffmpeg/ffmpeg.c
av_iformat_next was replaced with av_demuxer_iterate. https://trac.ffmpeg.org/wiki/Bump59
=> Fix build with ffmpeg 5.0+

conf.c
Without doing so OpenBSD's POSIX threads implementation will print "pthread_mutex_destroy on mutex with waiters!".
=> Make sure to unlock the mutex in conf_free() before calling mutex_free()

junklib.c
This breaks building with GNU iconv.
=> junklib: Do not define LIBICONV_PLUG for OpenBSD

Makefile.am
At one point INTL_LIBS was filled in by an autoconf test, but that was removed
with commit 70339732d8530570861d8fe26112b9f203077e91. This broke building on
OpenBSD. Fix the automake Makefile so it references a variable that is filled
out by the AM_GNU_GETTEXT macro.
=> Fix building with GNU intl

intl/dcigettext.c, intl/gettextP.h, plugins/shn/shn.c
With the upcoming clang 16 this is no longer supported.
Reference: https://archives.gentoo.org/gentoo-dev/message/dd9f2d3082b8b6f8dfbccb0639e6e240
=> Fix the build for clang 16

plugins/cocoaui/Playlist/PlaylistViewController.m
On current master, artwork in a centered column is not actually centered:
This PR resolves:
As a side benefit, it also resolves the same issue for right aligned images.
=> cocoaui: fix artwork center and right align when using high DPI displays

plugins/cocoaui/Playlist/PlaylistViewController.m
After further checking with a narrower image, https://github.com/DeaDBeeF-Player/deadbeef/pull/2875 wasn't quite right! It was calculating `art_x` in real display pixels rather than logical pixels, when the draw occurs in logical pixels. Sorry about that - it looked correct with an image that was only slightly narrower than the draw rect.
Updated examples below.
Old:
New:
=> cocoaui: fix centered artwork (try 2)

configure.ac, plugins/oss/oss.c
OpenBSD has not used OSS in quite awhile so remove checking for soundcard.h
outside of sys/, FreeBSD / NetBSD / DragonFly have the header in sys/.
=> oss: cleanup the header handling

plugins/cocoaui/Utility/TrackContextMenu.m
In macOS, adds a "Show in Finder" track context menu item, that opens the file location of the track in Finder.app
I was missing this feature from other music players (e.g. iTunes, VLC, IINA)
=> cocoaui: add "Show in Finder" context menu item

plugins/pltbrowser/pltbrowser.c
Adds a new event that shuffles the current playlist and then plays the first track. Also modifies the playlist double click setting to optionally use the new event.
The current implementation seems to always play the first track in the playlist and afterwards proceeds in the shuffle order but I'd prefer for the shuffling to determine the initial track, so I made this.
If you'd like something to be changed let me know.
=> Shuffle before play

plugins/converter/convgui.c
The `stock` string is accessed past its scope in the `gtk_list_store_set` call when the `if` condition is true, namely when `s` is assigned to `stock`.
=> Fix access to 'stock' string past scope

plugins/converter/converter.c
Calling `stat` repeatedly from multiple threads leads to race conditions, we should only call it if the directory already exists (i.e. errno set to EEXIST).
=> check_dir: mkdir first and if EEXIST check stat (avoid races conditions)

plugins/cocoaui/Utility/TrackContextMenu.m
fixes a uri/url confusion that would prevent the menu item from working sometimes. `[NSURL URLWithString:` would succeed on some path :URIs (that start with '/') and make URLs that didn't work with activateFileViewerSelectingURLs:
(The bug was my own from #2900 😅)
=> cocoaui: fix "Show in Finder" context menu item

plugins/aac/aac.c, plugins/alac/alac_plugin.c, plugins/ffap/ffap.c, plugins/ffmpeg/ffmpeg.c, plugins/flac/flac.c, plugins/mp3/mp3.c, plugins/musepack/musepack.c, plugins/opus/opus.c, plugins/psf/psfmain.c, plugins/shn/shn.c, plugins/sndfile/sndfile.c, plugins/tta/ttaplug.c, plugins/vorbis/vorbis.c, plugins/wavpack/wavpack.c, src/plmeta.c
On the linux CI system, the relevant format specifier for `int64_t` is `%ld`, rather than `%lld`. This generates some harmless warnings.
This PR changes current use of `%lld` with `int64_t` to use the portable `PRId64` constant instead, removing the warnings.
=> Cast to long long when printing %lld

plugins/gtkui/callbacks.h, plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c, plugins/gtkui/prefwin/prefwinsound.c, src/streamer.c
Add a bit depth selection box, similar to foobar.
Objective is to have a finer control of bit depth, which allows:
- Keep maximum resolution while doing volume math
- Lower resolution for testing/benchmark purpose
=> Add bit depth override option.

include/deadbeef/deadbeef.h, plugins/alsa/alsa.c, plugins/coreaudio/coreaudio.c, plugins/ffmpeg/ffmpeg.c, src/dsp.c, src/replaygain.c, src/streamer.c, src/viz.c
Based on @cqpwx's fork and https://github.com/marcoc1712/squeezelite-R2/blob/Release/dsd.c
Tested both DSF and DFF format.
To use it check `Enable DoP output` option in ffmpeg plugin.
=> Add experimental DoP support.

scripts/test.sh
by setting `TEST_CPP_SOURCES` from the arguments to `test.sh`, if any, we can select to compile & run only some test suites. e.g., `./scripts/test.sh TitleFormatting TrackSwitching`. if no arguments are provided all test suites are selected.
=> test: allowing selecting test suites

scripts/test.sh
previously `test.sh` used `set -e` to exit if compiling the tests OR running them failed. this meant that the cpp libs had to be restored manually, as the final line of the script was not reached. by refactoring compilation into its own function and checking its return code, we can exit only when compilation fails. in this event, cpp libs are restored.
=> test: restore cpp libs even if tests fail

src/dsp.c
Use the `ensure_dsp_temp_buffer` function instead of allocating and leaking a buffer on every audio frame.
=> dsp: fix memory leak in DoP code

deadbeef.desktop.in
The action identifiers may not contain spaces, only [A-Za-z0-9-]
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions-identifier
=> Fix deadbeef.desktop launcher

scripts/test.sh
246e3b1 introduced a bug in the test script. If the test suite fails the script still continues, restores the cpp libs that were moved out of the `static-deps` folder, and exits with the exit code of that move. This hides failing or crashing tests from CI. Oops. Luckily it's easily fixed.
=> tests: propagate exit code from running tests properly

Tests.mk, scripts/test.sh
This saves us from a lot of recompilation overhead during development. It also lets us build faster due parallelising with `make -j`.
=> tests: refactor build logic into a Makefile

Tests/AlbumNavigationTests.cpp, Tests/TestData/AlbumNavigation.csv, include/deadbeef/deadbeef.h, plugins/hotkeys/hotkeys.c, src/main.c, src/playlist.c, src/playlist.h, src/streamer.c, src/streamer.h
This pull request implements commands that can be bound to hotkeys: `Playback/Play Next Album`,  `Playback/Play Previous Album`, `Playback/Play Random Album`. The latter goes to first track of a random album in the current playlist. The behaviour of the first two depends on the shuffle setting and is as follows.
* `DDB_SHUFFLE_RANDOM`, `DDB_SHUFFLE_TRACKS`: same as  Play Next Track and Play Previous Track.
* `DDB_SHUFFLE_OFF`, `DDB_SHUFFLE_ALBUMS`:
*  * Play Next Album is the same as calling Play Next Track until reaching a new album.
* * If *not* on the first track of the current album, Play Previous Track goes to the first track on the current album
* * If on the first track of the current album, Play Previous Track is the same as calling Play Previous Track until reaching the first …
=> feat: commands for next/previous album that respect shuffle settings

src/plugins.c
There is undefined behavior for some specific folder configurations:
- `xdg_plugin_dir_explicit_arch` is not initialized in some cases
If `xdg_plugin_dir` and  `dirname` is the same then both are ignored (since `while` loop will exit early). Comment suggests that we just want to skip loading same dir twice.
=> Plugin directory selection fixes

plugins/cdda/cdda.c
Since cdio API version 6 (introduced in 2012) the magic track index 0 represents the album wide CD-TEXT. Trying to read album artist / title from the track_nr index will result in the track artist / track title being selected.
Having the Artist - Album playlist column enabled and relying on CD-TEXT would previously display the track title instead of the album title after the dash.
API ref: http://git.savannah.gnu.org/cgit/libcdio.git/tree/include/cdio/cdtext.h#n305
Example using the Memory Garden - 1349 CD with CD-Text, added to playlist before and after fix:
=> plugins: cdda: cdtext: Try reading magic track 0 first for album artist / title

include/deadbeef/deadbeef.h
`streamer_get_playing_track_safe` is available if `DDB_API_LEVEL >= 16` (API version 1.16), but `streamer_get_playing_track` is defined with `DEPRECATED_16` (deprecate if API version >= 1.6). `DEPRECATED_116` should be used instead.
=> deadbeef.h: fix too early deprecation of streamer_get_playing_track

plugins/ffmpeg/ffmpeg.c
Added some const attributes here and there to satisfy some warnings, conditionally used new structures for the channel count based on an API deprecated long enough ago to be dropped in 7.0. Maybe you'll want to restyle it to your ideal, if you prefer.
=> ffmpeg: update API to support FFMPEG 7

src/playlist.c
the plugin save() function was not being called according to its API. hence plugins could get different results trying to save a playlist range as DBPL vs M3U.
=> fix: playlist plugins were not saving ranges correctly

Tests.mk
b2f8c9905a changed tests to run in a temporary folder to avoid creating output files that would have to be `.gitignore`d (#3119). if this directory already exists, however, the test script fails. passing `-p` to `mkdir` fixes this.
=> fix: test script doesn't fail if output directory already exists

src/playlist.c
plt_load_from_buffer calls _plt_load_from_file with fname=NULL, which basically just unconditionally crashes.
Anyway, drag-and-drop from the sidebar into a playlist was broken on macOS beacause of this. Seems to be fine with this fix.
=> fix plt_load_from_buffer

Tests.mk, Tests/PlaylistTests.cpp, src/pltmeta.h, src/sort.h
This PR is a draft to resolve #3127. It adds tests for sorting playlists directly and with autosort, plus some tweaks to the test suite (build with debuginfo, link with lld for better error messages).
=> fix #3127 (autosort)

Tests/MP3DecoderTests.cpp
on arm64/aarch64 libmpg123 generates bad data leading to the test MP3DecoderTests.test_DecodeMP3As2PiecesMPG123_SameAs1Piece failing. this test was excluded by testing for the `TARGET_CPU_ARM64` macro. but this is an Xcode macro defined in `TargetConditionals.h`. thus the test would not be excluded when compiling on a device such as the Raspberry Pi 4 or 5. the portable way to test for arm64 architecture with clang is to check for `__aarch64__`: https://stackoverflow.com/a/41666292
=> fix: test for arm64 architecture properly in MP3DecoderTests

deadbeef.desktop.in
It fixes the issue where app icon is not being shown in dash for Gnome.
=> Update .desktop file with `StartupWMClass`

plugins/ffap/ffap.c
Found a corrupted APE file :)
OS: macos Sequoia 15.5, arm64
=> Check for equality of the APE frames count to zero

travis/build.sh
winpthread had ABI breaking change, newest, recompiled version of dispatch should fix it
=> Windows: update dispatch (fixes #3202)

.github/workflows/windowsbuild.yml
needed because `windows-2025` (which will become `windows-latest` next month) does not come with Inno Setup preinstalled
=> Install Inno Setup on windows runner

plugins/gtkui/callbacks.h, plugins/gtkui/deadbeef.glade, plugins/gtkui/interface.c, plugins/gtkui/prefwin/prefwinplayback.c, src/main.c
Cocoaui settings entry is missing. I guess translations would need to be updated as well.
=> Add option to always resume session in paused state (fixes #3222)
